# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_guest_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guest',
            new_name='User',
        ),
    ]
